"""added on delete cascade for required tables

Revision ID: 03f14af14be7
Revises: 4e6b8ad8f1bb
Create Date: 2025-07-11 13:52:58.524343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f14af14be7'
down_revision: Union[str, None] = '4e6b8ad8f1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('listening_history_ibfk_2', 'listening_history', type_='foreignkey')
    op.create_foreign_key(None, 'listening_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_liked_music_ibfk_1', 'user_liked_music', type_='foreignkey')
    op.drop_constraint('user_liked_music_ibfk_2', 'user_liked_music', type_='foreignkey')
    op.create_foreign_key(None, 'user_liked_music', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_liked_music', 'music', ['music_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_liked_playlists_ibfk_1', 'user_liked_playlists', type_='foreignkey')
    op.drop_constraint('user_liked_playlists_ibfk_2', 'user_liked_playlists', type_='foreignkey')
    op.create_foreign_key(None, 'user_liked_playlists', 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_liked_playlists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_liked_playlists', type_='foreignkey')
    op.drop_constraint(None, 'user_liked_playlists', type_='foreignkey')
    op.create_foreign_key('user_liked_playlists_ibfk_2', 'user_liked_playlists', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_liked_playlists_ibfk_1', 'user_liked_playlists', 'playlists', ['playlist_id'], ['id'])
    op.drop_constraint(None, 'user_liked_music', type_='foreignkey')
    op.drop_constraint(None, 'user_liked_music', type_='foreignkey')
    op.create_foreign_key('user_liked_music_ibfk_2', 'user_liked_music', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_liked_music_ibfk_1', 'user_liked_music', 'music', ['music_id'], ['id'])
    op.drop_constraint(None, 'listening_history', type_='foreignkey')
    op.create_foreign_key('listening_history_ibfk_2', 'listening_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
