"""added colum for zip_s3 url in license table

Revision ID: 46a15d7d5717
Revises: 6cf8fd88480c
Create Date: 2025-09-08 18:26:43.448355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a15d7d5717'
down_revision: Union[str, None] = '6cf8fd88480c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('zip_s3_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'zip_s3_key')
    # ### end Alembic commands ###
