"""Add likes_count and constraints

Revision ID: 4aa353feda86
Revises: 596c6d20e0d1
Create Date: 2025-06-24 18:06:48.360535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa353feda86'
down_revision: Union[str, None] = '596c6d20e0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('playlists', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.create_unique_constraint('uix_user_music_like', 'user_liked_music', ['user_id', 'music_id'])
    op.create_unique_constraint('uix_user_playlist_like', 'user_liked_playlists', ['user_id', 'playlist_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_playlist_like', 'user_liked_playlists', type_='unique')
    op.drop_constraint('uix_user_music_like', 'user_liked_music', type_='unique')
    op.drop_column('playlists', 'likes_count')
    op.drop_column('music', 'likes_count')
    # ### end Alembic commands ###
