"""Updated coupans table

Revision ID: 4d30aac7bd40
Revises: 562662b89f17
Create Date: 2025-09-03 17:40:32.990314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d30aac7bd40'
down_revision: Union[str, None] = '562662b89f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('applies_to_entity', sa.Enum('GLOBAL', 'MUSIC', 'LICENSE', name='couponscope'), nullable=True))
    op.add_column('coupons', sa.Column('applies_to_id', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('max_redemptions', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'expires_at')
    op.drop_column('coupons', 'max_redemptions')
    op.drop_column('coupons', 'applies_to_id')
    op.drop_column('coupons', 'applies_to_entity')
    # ### end Alembic commands ###
