"""Fixed the foreign key issues in music for delete

Revision ID: 4e6b8ad8f1bb
Revises: 3097ff48fc3c
Create Date: 2025-07-11 13:43:30.064212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6b8ad8f1bb'
down_revision: Union[str, None] = '3097ff48fc3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('listening_history_ibfk_1', 'listening_history', type_='foreignkey')
    op.create_foreign_key(None, 'listening_history', 'music', ['music_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listening_history', type_='foreignkey')
    op.create_foreign_key('listening_history_ibfk_1', 'listening_history', 'music', ['music_id'], ['id'])
    # ### end Alembic commands ###
