"""Add license PDF fields

Revision ID: 559ff199d185
Revises: e6b58c729403
Create Date: 2025-12-03 16:31:35.595902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '559ff199d185'
down_revision: Union[str, None] = 'e6b58c729403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The following legacy playlist index/table drops can fail due to FK constraints in MySQL.
    # They are unrelated to the license PDF fields; guard them to avoid blocking this migration.
    try:
        op.drop_index('uix_user_playlist_like', table_name='user_liked_playlists')
        op.drop_table('user_liked_playlists')
    except Exception:
        pass
    op.add_column('user_licenses', sa.Column('license_id_formatted', sa.String(length=50), nullable=True))
    op.add_column('user_licenses', sa.Column('pdf_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_licenses', sa.Column('pdf_checksum', sa.String(length=64), nullable=True))
    op.add_column('user_licenses', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('user_licenses', sa.Column('transaction_id', sa.String(length=255), nullable=True))
    op.add_column('user_licenses', sa.Column('buyer_ip', sa.String(length=50), nullable=True))
    op.add_column('user_licenses', sa.Column('buyer_user_agent', sa.String(length=500), nullable=True))
    op.add_column('user_licenses', sa.Column('amount_paid', sa.Float(), nullable=True))
    op.add_column('user_licenses', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('user_licenses', sa.Column('discount_applied', sa.Float(), nullable=True))
    op.add_column('user_licenses', sa.Column('payment_method', sa.String(length=100), nullable=True))
    op.alter_column('user_licenses', 'license_pdf_path',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.create_index(op.f('ix_user_licenses_license_id_formatted'), 'user_licenses', ['license_id_formatted'], unique=True)
    op.create_foreign_key(None, 'user_licenses', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_licenses', type_='foreignkey')
    op.drop_index(op.f('ix_user_licenses_license_id_formatted'), table_name='user_licenses')
    op.alter_column('user_licenses', 'license_pdf_path',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('user_licenses', 'payment_method')
    op.drop_column('user_licenses', 'discount_applied')
    op.drop_column('user_licenses', 'currency')
    op.drop_column('user_licenses', 'amount_paid')
    op.drop_column('user_licenses', 'buyer_user_agent')
    op.drop_column('user_licenses', 'buyer_ip')
    op.drop_column('user_licenses', 'transaction_id')
    op.drop_column('user_licenses', 'order_id')
    op.drop_column('user_licenses', 'pdf_checksum')
    op.drop_column('user_licenses', 'pdf_generated_at')
    op.drop_column('user_licenses', 'license_id_formatted')
    op.create_table('user_liked_playlists',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('playlist_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('liked_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name='user_liked_playlists_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_liked_playlists_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uix_user_playlist_like', 'user_liked_playlists', ['user_id', 'playlist_id'], unique=True)
    # ### end Alembic commands ###
