"""Created coupans

Revision ID: 562662b89f17
Revises: 2d859cf8cb07
Create Date: 2025-09-03 16:09:34.720196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562662b89f17'
down_revision: Union[str, None] = '2d859cf8cb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stripe_coupon_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_promotion_code_id', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENT', 'FIXED_AMOUNT', name='discounttype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_stripe_coupon_id'), 'coupons', ['stripe_coupon_id'], unique=True)
    op.create_index(op.f('ix_coupons_stripe_promotion_code_id'), 'coupons', ['stripe_promotion_code_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupons_stripe_promotion_code_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_stripe_coupon_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
