"""Added user id and an foreignkey

Revision ID: 6051be449865
Revises: de919fe5f2b7
Create Date: 2025-05-21 18:21:30.550894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6051be449865'
down_revision: Union[str, None] = 'de919fe5f2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'music', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'music', type_='foreignkey')
    op.drop_column('music', 'user_id')
    # ### end Alembic commands ###
