"""add process_id and is_remaster to mastered_music

Revision ID: 85e326e05b86
Revises: 9886c9eaa4db
Create Date: 2026-02-06 11:22:19.448288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e326e05b86'
down_revision: Union[str, None] = '9886c9eaa4db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mastered_music', sa.Column('process_id', sa.String(length=100), nullable=True))
    op.add_column('mastered_music', sa.Column('is_remaster', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mastered_music', 'is_remaster')
    op.drop_column('mastered_music', 'process_id')
    # ### end Alembic commands ###
