"""refine_marketing_ads_model

Revision ID: 9886c9eaa4db
Revises: 17e854f93e3b
Create Date: 2026-02-05 20:35:31.507942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9886c9eaa4db'
down_revision: Union[str, None] = '17e854f93e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_ads', sa.Column('item_description', sa.Text(), nullable=True))
    op.drop_column('marketing_ads', 'price')
    op.drop_column('marketing_ads', 'sale_price')
    op.drop_column('marketing_ads', 'is_on_sale')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_ads', sa.Column('is_on_sale', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('marketing_ads', sa.Column('sale_price', mysql.FLOAT(), nullable=True))
    op.add_column('marketing_ads', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.drop_column('marketing_ads', 'item_description')
    # ### end Alembic commands ###
