"""Made mp3 music as an optional

Revision ID: a4e0ad339250
Revises: f99b3a74b7e6
Create Date: 2025-07-14 18:13:11.427774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a4e0ad339250'
down_revision: Union[str, None] = 'f99b3a74b7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'mp3_url',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'mp3_url',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
