"""Added cover-image coloum in music

Revision ID: a6ce7a3e2437
Revises: d8b029a9eb1f
Create Date: 2025-05-15 15:34:39.721026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ce7a3e2437'
down_revision: Union[str, None] = 'd8b029a9eb1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'cover_image_url')
    # ### end Alembic commands ###
