"""add_original_music_url_to_mastered_music

Revision ID: aace2e0935c4
Revises: e9120721ede9
Create Date: 2026-02-05 17:37:31.513999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aace2e0935c4'
down_revision: Union[str, None] = 'e9120721ede9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mastered_music', sa.Column('original_music_url', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mastered_music', 'original_music_url')
    # ### end Alembic commands ###
