"""Added Music and Licens Tables

Revision ID: d8b029a9eb1f
Revises: 432354acb422
Create Date: 2025-05-15 13:08:24.144079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b029a9eb1f'
down_revision: Union[str, None] = '432354acb422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('album', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=255), nullable=False),
    sa.Column('track_type', sa.String(length=255), nullable=False),
    sa.Column('mood', sa.String(length=255), nullable=False),
    sa.Column('instruments', sa.String(length=255), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('mp3_url', sa.String(length=500), nullable=False),
    sa.Column('wav_url', sa.String(length=500), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('release_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('license_type', sa.Enum('leasing', 'unlimited', 'exclusive', name='licensetypesenum'), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('terms', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licenses')
    op.drop_table('music')
    # ### end Alembic commands ###
