"""Added is_free coloum in the music

Revision ID: de919fe5f2b7
Revises: a6ce7a3e2437
Create Date: 2025-05-20 18:18:46.489819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de919fe5f2b7'
down_revision: Union[str, None] = 'a6ce7a3e2437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('is_free', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'is_free')
    # ### end Alembic commands ###
