"""Create mastered_music table

Revision ID: e9120721ede9
Revises: 6418ad7618ea
Create Date: 2026-01-16 12:58:42.950467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9120721ede9'
down_revision: Union[str, None] = '6418ad7618ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mastered_music',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('mastered_url', sa.String(length=500), nullable=False),
    sa.Column('original_lufs', sa.Float(), nullable=False),
    sa.Column('target_lufs', sa.Float(), nullable=False),
    sa.Column('profile', sa.String(length=50), nullable=False),
    sa.Column('quality_mode', sa.String(length=20), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('bit_depth', sa.String(length=50), nullable=False),
    sa.Column('processing_time', sa.Float(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mastered_music')
    # ### end Alembic commands ###
