"""added on delete cascade for required tables

Revision ID: f99b3a74b7e6
Revises: 03f14af14be7
Create Date: 2025-07-11 14:16:20.053226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99b3a74b7e6'
down_revision: Union[str, None] = '03f14af14be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('licenses_ibfk_1', 'licenses', type_='foreignkey')
    op.create_foreign_key(None, 'licenses', 'music', ['music_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('playlist_music_ibfk_1', 'playlist_music', type_='foreignkey')
    op.drop_constraint('playlist_music_ibfk_2', 'playlist_music', type_='foreignkey')
    op.create_foreign_key(None, 'playlist_music', 'music', ['music_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'playlist_music', 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlist_music', type_='foreignkey')
    op.drop_constraint(None, 'playlist_music', type_='foreignkey')
    op.create_foreign_key('playlist_music_ibfk_2', 'playlist_music', 'playlists', ['playlist_id'], ['id'])
    op.create_foreign_key('playlist_music_ibfk_1', 'playlist_music', 'music', ['music_id'], ['id'])
    op.drop_constraint(None, 'licenses', type_='foreignkey')
    op.create_foreign_key('licenses_ibfk_1', 'licenses', 'music', ['music_id'], ['id'])
    # ### end Alembic commands ###
